// ⚠️ This file is auto-generated by wall-e (https://github.com/1712n/wall-e/).
// Do not edit it directly — instead, update the associated test/index.spec.* file and regenerate the code.

import { Client } from "pg";

interface Env {
  AI: Ai;
  HYPERDRIVE: Hyperdrive;
}

interface MessageRow {
  id: number;
  content: string;
}

interface SimilarityRow {
  message_id: number;
  topic: string;
  industry: string;
  similarity: number;
}

export default {
  async scheduled(
    event: ScheduledEvent,
    env: Env,
    ctx: ExecutionContext,
  ): Promise {
    const client = new Client({
      connectionString: env.HYPERDRIVE.connectionString,
      connectionTimeoutMillis: 30000,
      query_timeout: 30000,
    });
    try {
      await client.connect();
      console.log("INFO: DB connected");
      const messages = await fetchMessages(client);
      if (messages.length === 0) {
        console.log("INFO: No messages to process");
        return;
      }
      console.log(`INFO: Processing ${messages.length} messages`);
      const embeddings = await generateEmbeddings(env, messages);
      await updateEmbeddings(client, messages, embeddings);
      const similarities = await calculateSimilarities(
        client,
        messages.map((m) => m.id),
      );
      await insertScores(client, similarities);
      console.log("INFO: Processing complete");
    } catch (error) {
      console.error(
        `ERROR: Worker failed: ${error instanceof Error ? error.message : String(error)}`,
      );
      throw error;
    } finally {
      try {
        await client.end();
        console.log("INFO: DB connection closed");
      } catch (error) {
        console.error(
          `ERROR: Failed to close DB: ${error instanceof Error ? error.message : String(error)}`,
        );
      }
    }
  },
};

async function fetchMessages(client: Client): Promise<MessageRow[]> {
  try {
    const query = `
      SELECT DISTINCT um.id, um.content
      FROM unique_messages um
      INNER JOIN message_feed mf ON um.id = mf.message_id
      WHERE um.embedding IS NULL
        AND um.content != ''
        AND mf.timestamp >= NOW() - INTERVAL '1 day'
      LIMIT 100
    `;
    const result = await client.query(query);
    console.log(`INFO: Fetched ${result.rows.length} messages`);
    return result.rows;
  } catch (error) {
    console.error(
      `ERROR: fetchMessages failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    throw error;
  }
}

async function generateEmbeddings(
  env: Env,
  messages: MessageRow[],
): Promise<number[][]> {
  try {
    const texts = messages.map((m) => m.content);
    const resp = await env.AI.run("@cf/baai/bge-m3", { text: texts });
    if (!resp.data || !Array.isArray(resp.data)) {
      throw new Error("Invalid AI response");
    }
    console.log(`INFO: Generated ${resp.data.length} embeddings`);
    return resp.data;
  } catch (error) {
    console.error(
      `ERROR: generateEmbeddings failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    throw error;
  }
}

async function updateEmbeddings(
  client: Client,
  messages: MessageRow[],
  embeddings: number[][],
): Promise {
  try {
    for (let i = 0; i < messages.length; i++) {
      const formattedEmbedding = `[${embeddings[i].join(",")}]`;
      await client.query(
        "UPDATE unique_messages SET embedding = $1 WHERE id = $2",
        [formattedEmbedding, messages[i].id],
      );
    }
    console.log(`INFO: Updated ${messages.length} embeddings`);
  } catch (error) {
    console.error(
      `ERROR: updateEmbeddings failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    throw error;
  }
}

async function calculateSimilarities(
  client: Client,
  messageIds: number[],
): Promise<SimilarityRow[]> {
  try {
    const query = `
      SELECT DISTINCT ON (m.id, s.topic, s.industry)
        m.id as message_id,
        s.topic,
        s.industry,
        1 - (m.embedding <=> s.embedding) AS similarity
      FROM unique_messages m
      CROSS JOIN synth_data_prod s
      WHERE m.id = ANY($1::int[])
        AND m.embedding IS NOT NULL
        AND s.embedding IS NOT NULL
      ORDER BY m.id, s.topic, s.industry, m.embedding <=> s.embedding
    `;
    const result = await client.query(query, [messageIds]);
    console.log(`INFO: Calculated ${result.rows.length} similarities`);
    return result.rows;
  } catch (error) {
    console.error(
      `ERROR: calculateSimilarities failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    throw error;
  }
}

async function insertScores(
  client: Client,
  similarities: SimilarityRow[],
): Promise {
  if (similarities.length === 0) {
    console.log("INFO: No scores to insert");
    return;
  }
  try {
    const values = similarities
      .map(
        (s, i) =>
          `($${i * 4 + 1}, $${i * 4 + 2}, $${i * 4 + 3}, $${i * 4 + 4})`,
      )
      .join(",");
    const params = similarities.flatMap((s) => [
      s.topic,
      s.industry,
      s.message_id,
      s.similarity,
    ]);
    const query = `
      INSERT INTO message_scores (topic, industry, message_id, similarity, main)
      VALUES ${values}
      ON CONFLICT (message_id, topic, industry)
      DO UPDATE SET similarity = EXCLUDED.similarity, main = COALESCE(message_scores.main, EXCLUDED.similarity)
    `;
    await client.query(query, params);
    console.log(`INFO: Inserted ${similarities.length} scores`);
  } catch (error) {
    console.error(
      `ERROR: insertScores failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    throw error;
  }
}
